import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'antd/dist/reset.css';
import '../../public/antd.min.css';
import AuthCheckLayout from '@bp1/components/layout/AuthCheckLayout';
import AuthSessionProvider from '@bp1/components/layout/AuthSessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider>
          <AuthCheckLayout>{props.children}</AuthCheckLayout>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
